/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shirt_pbr.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shirt_pbr.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['t-shirt_back'].geometry} material={materials.shirt} />
      <mesh geometry={nodes['t-shirt_inside'].geometry} material={materials.shirt_inside} />
      <mesh geometry={nodes['t-shirt_sleeve_left'].geometry} material={materials.shirt} />
      <mesh geometry={nodes['t-shirt_sleeve_right'].geometry} material={materials.shirt} />
      <mesh geometry={nodes['t-shirt_front'].geometry} material={materials.shirt} />
      <mesh geometry={nodes['t-shirt_collar'].geometry} material={materials.shirt} />
    </group>
  )
}

useGLTF.preload('/shirt_pbr.gltf')
